#!/bin/sh
# Lint staged files
npx lint-staged

# Scan for secrets
"$HOME/AppData/Local/Microsoft/WinGet/Packages/Gitleaks.Gitleaks_Microsoft.Winget.Source_8wekyb3d8bbwe/gitleaks.exe" detect --source . --verbose
